version: "2"
services:
  tnt: { image: "tarantool/tarantool:1.7" }

  tnt_node:
    extends: { service: "tnt" }
    command: "tarantool /cfg/conf.lua"
    environment:
      - "TARANTOOL_PORT=3301"
      - "TARANTOOL_USER_NAME=admin"
      - "TARANTOOL_USER_PASSWORD=password"
      - "TARANTOOL_REPLICATION_SOURCE=replicator:password@node1:3301,replicator:password@node2:3301"
    volumes: [ "./cfg:/cfg" ]

  console:
    extends: { service: "tnt" }
    entrypoint: "sh"

  node1:
    extends: { service: "tnt_node" }

  node2:
    extends: { service: "tnt_node" }
